# Generated by Django 4.1.5 on 2023-02-07 13:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cnabs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="arquivomodel",
            name="data",
        ),
        migrations.AddField(
            model_name="arquivomodel",
            name="date",
            field=models.CharField(
                default=1,
                max_length=8,
                validators=[django.core.validators.MinLengthValidator(8)],
            ),
            preserve_default=False,
        ),
    ]
