# Generated by Django 4.1.5 on 2023-02-07 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cnabs", "0002_remove_arquivomodel_data_arquivomodel_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="arquivomodel",
            old_name="date",
            new_name="data",
        ),
    ]
