# Generated by Django 4.1.5 on 2023-02-07 13:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cnabs", "0003_rename_date_arquivomodel_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arquivomodel",
            name="hora",
            field=models.CharField(
                max_length=6, validators=[django.core.validators.MinLengthValidator(6)]
            ),
        ),
    ]
